// examples/svelte/src/renderers/Page.svelte
<script lang="ts">
  import type { ResolvedError } from '@sanghyuk-2i/huh-core';

  interface Props {
    error: ResolvedError;
    onAction: () => void;
    onDismiss: () => void;
  }

  let { error, onAction }: Props = $props();
</script>

<div class="error-page">
  {#if error.image}
    <img src={error.image} alt="" />
  {/if}
  <h1>{error.title}</h1>
  <p>{error.message}</p>
  {#if error.action}
    <button onclick={onAction}>{error.action.label}</button>
  {/if}
</div>

// examples/react/src/renderers.tsx
import type { RendererMap } from '@sanghyuk-2i/huh-react';

export const renderers: RendererMap = {
  TOAST: ({ error, onDismiss }) => (
    <div className="toast" onClick={onDismiss}>
      {error.message}
    </div>
  ),

  MODAL: ({ error, onAction, onDismiss }) => (
    <div className="modal-overlay" onClick={onDismiss}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <h2>{error.title}</h2>
        <p>{error.message}</p>
        <div className="modal-actions">
          <button className="btn-secondary" onClick={onDismiss}>
            닫기
          </button>
          {error.action && <button onClick={onAction}>{error.action.label}</button>}
        </div>
      </div>
    </div>
  ),

  PAGE: ({ error, onAction }) => (
    <div className="error-page">
      {error.image && <img src={error.image} alt="" />}
      <h1>{error.title}</h1>
      <p>{error.message}</p>
      {error.action && <button onClick={onAction}>{error.action.label}</button>}
    </div>
  ),
};
