// examples/react/src/renderers.js
import { jsx as _jsx, jsxs as _jsxs } from 'react/jsx-runtime';
export const renderers = {
  TOAST: ({ error, onDismiss }) =>
    _jsx('div', { className: 'toast', onClick: onDismiss, children: error.message }),
  MODAL: ({ error, onAction, onDismiss }) =>
    _jsx('div', {
      className: 'modal-overlay',
      onClick: onDismiss,
      children: _jsxs('div', {
        className: 'modal',
        onClick: (e) => e.stopPropagation(),
        children: [
          _jsx('h2', { children: error.title }),
          _jsx('p', { children: error.message }),
          _jsxs('div', {
            className: 'modal-actions',
            children: [
              _jsx('button', {
                className: 'btn-secondary',
                onClick: onDismiss,
                children: '\uB2EB\uAE30',
              }),
              error.action && _jsx('button', { onClick: onAction, children: error.action.label }),
            ],
          }),
        ],
      }),
    }),
  PAGE: ({ error, onAction }) =>
    _jsxs('div', {
      className: 'error-page',
      children: [
        error.image && _jsx('img', { src: error.image, alt: '' }),
        _jsx('h1', { children: error.title }),
        _jsx('p', { children: error.message }),
        error.action && _jsx('button', { onClick: onAction, children: error.action.label }),
      ],
    }),
};

// examples/svelte/src/renderers/Page.svelte
<script lang="ts">
  import type { ResolvedError } from '@huh/core';

  interface Props {
    error: ResolvedError;
    onAction: () => void;
    onDismiss: () => void;
  }

  let { error, onAction }: Props = $props();
</script>

<div class="error-page">
  {#if error.image}
    <img src={error.image} alt="" />
  {/if}
  <h1>{error.title}</h1>
  <p>{error.message}</p>
  {#if error.action}
    <button onclick={onAction}>{error.action.label}</button>
  {/if}
</div>
